; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1

.export _music_data_bau_bau_d_victory:=music_data_bau_bau_d_victory

music_data_bau_bau_d_victory:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : BAU BAU :D (Victory)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_bau_bau_d_victory
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env6,@env8,@env0 ; 00 : DPCM Phase Bass
	.word @env3,@env6,@env7,@env0 ; 01 : Fade
	.word @env1,@env6,@env7,@env0 ; 02 : Noise Percussion 1
	.word @env5,@env6,@env4,@env0 ; 03 : Noise Cymbal 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $cc,$c0,$c4,$c4,$c8,$02,$c9,$c8,$00,$06
@env3:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$10
@env4:
	.byte $c1,$03,$c0,$02,$c0,$c0,$00,$04
@env5:
	.byte $00,$cf,$03,$ce,$03,$cd,$03,$cc,$03,$cb,$03,$ca,$03,$c9,$03,$c8,$03,$c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$03,$c0,$00,$1f
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c0,$00,$07
@env10:
	.byte $cc,$c0,$00,$01

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $4f, $02, $80, $19, $87, $1b, $87, $1d, $87, $1e, $87, $1b, $87, $1d, $87, $1e, $87, $20, $87, $1d, $87, $1e, $87, $20
	.byte $87, $22, $87, $48, $24, $87, $82, $25, $eb, $44, $00
@song0ch1:
	.byte $4e, $01
	.byte $41, $18
	.word @song0ref1
	.byte $24, $87, $4e, $00, $82, $29, $eb, $44, $00
@song0ch2:
	.byte $80, $31, $87, $33, $87, $35, $87, $36, $87, $33, $87, $35, $87, $36, $87, $38, $87, $35, $87, $36, $87, $38, $87, $3a
	.byte $87, $3c, $87, $82, $3d, $eb, $44, $00
@song0ch3:
	.byte $4b, .lobyte(@env10), .hibyte(@env10), $84, $0d
@song0ref90:
	.byte $87, $4d, $13, $87, $4d, $13, $87, $4d, $13, $87, $4d, $0f
	.byte $41, $08
	.word @song0ref90
	.byte $87, $4d, $13, $87, $4d, $13, $87, $4d, $13, $87, $4d, $0d, $87, $4b, .lobyte(@env2), .hibyte(@env2), $86, $1a, $eb
	.byte $44, $00
@song0ch4:
	.byte $f7, $f7, $44, $00
