; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1

.export _music_data_almost_there_world_5_map:=music_data_almost_there_world_5_map

music_data_almost_there_world_5_map:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Almost There! (World 5 Map)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_almost_there_world_5_map
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env11,@env14,@env2 ; 00 : Triangle Drums
	.word @env8,@env10,@env13,@env18 ; 01 : Recca Tri Note OFF
	.word @env1,@env11,@env13,@env0 ; 02 : Noise Percussion 1
	.word @env3,@env11,@env13,@env0 ; 03 : Noise Percussion 2
	.word @env15,@env11,@env14,@env0 ; 04 : DPCM Phase Bass
	.word @env16,@env19,@env4,@env0 ; 05 : Lead 2
	.word @env20,@env19,@env7,@env0 ; 06 : Slap Bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $80,$ff,$00,$01
@env3:
	.byte $00,$cf,$ca,$c5,$c0,$00,$04
@env4:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env5:
	.byte $00,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$00,$01
@env6:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$03,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$01
@env7:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env10:
	.byte $c0,$7f,$7f,$c1,$00,$00
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $c0,$05,$c1,$05,$c2,$05,$c3,$05,$c2,$05,$c1,$04,$c1,$00,$00
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c0,$00,$07
@env16:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env17:
	.byte $fc,$80,$c0,$00,$02
@env18:
	.byte $00,$ce,$7f,$00,$02
@env19:
	.byte $cc,$c0,$00,$01
@env20:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$0c,$40 ; 00 abyssgarding_dmc 3 - flixelNote v1 E# (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$09,$40 ; 01 flixelNote v1 D (Pitch:9)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$0c,$40 ; 02 flixelNote v1 D (Pitch:12)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$08,$40 ; 03 flixelNote v1 D# (Pitch:8)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$09,$40 ; 04 flixelNote v1 D# (Pitch:9)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0a,$40 ; 05 flixelNote v1 D# (Pitch:10)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0b,$40 ; 06 flixelNote v1 D# (Pitch:11)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0d,$40 ; 07 flixelNote v1 D# (Pitch:13)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$09,$40 ; 08 flixelNote v1 E (Pitch:9)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0c,$40 ; 09 flixelNote v1 E (Pitch:12)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $88
@song0ref2:
	.byte $1e, $ad, $20, $95, $22, $95, $27, $95, $25, $95, $48, $23, $ad, $20, $95, $22, $95, $23, $95, $22, $95, $48, $20, $dd
	.byte $22, $ad, $48, $25, $95, $23, $95, $22, $95, $23, $95, $22, $95, $20, $95, $48
	.byte $41, $14
	.word @song0ref2
@song0ref45:
	.byte $48, $27, $95, $25, $95, $2a, $95, $29, $89, $28, $89, $25, $ad, $48, $22, $95, $20, $95, $25, $95, $24, $89, $23, $89
	.byte $22, $95, $1e, $95
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7b, $8a
	.byte $41, $24
	.word @song0ref2
	.byte $48
	.byte $41, $14
	.word @song0ref2
	.byte $41, $16
	.word @song0ref45
	.byte $50, $0b, $2e, $2a, $95, $43, $1e, $95, $42
	.word @song0ch0loop
@song0ch1:
	.byte $88
@song0ref101:
	.byte $12, $c5, $14, $ad, $16, $95, $19, $ad, $17, $95, $16, $95, $14, $ad, $20, $89, $1e, $89, $1d, $89, $1b, $89, $19, $89
	.byte $17, $89, $16, $89, $14, $95, $16, $a1, $12, $ad, $17, $95, $16, $89, $15, $89, $14, $ad
	.byte $41, $2a
	.word @song0ref101
@song0ch1loop:
	.byte $8c
	.byte $41, $2a
	.word @song0ref101
	.byte $41, $2a
	.word @song0ref101
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $88, $1e, $c5, $20, $ad, $22, $95, $25, $ad, $23, $95, $22, $95, $20, $ad, $2c, $89, $2a, $89, $29, $89, $27, $89, $25
	.byte $89, $23, $89, $22, $89, $20, $95, $22, $a1, $1e, $ad, $23, $95, $22, $89, $21, $89, $20, $ad
	.byte $41, $2a
	.word @song0ref101
@song0ch2loop:
@song0ref204:
	.byte $80, $25, $89, $82, $40, $0a, $89, $80, $25, $89, $82, $40, $0a, $89, $80, $31, $89, $82, $40, $0a, $89, $80, $25, $89
	.byte $31, $89, $25, $89, $82, $40, $0a, $89, $80, $31, $89, $82, $40, $0a, $89
	.byte $41, $18
	.word @song0ref204
	.byte $41, $18
	.word @song0ref204
	.byte $41, $18
	.word @song0ref204
	.byte $41, $18
	.word @song0ref204
	.byte $41, $18
	.word @song0ref204
	.byte $41, $18
	.word @song0ref204
	.byte $41, $18
	.word @song0ref204
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ref267:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
@song0ch3loop:
	.byte $4c, $4b, .lobyte(@env19), .hibyte(@env19)
@song0ref288:
	.byte $4f, $00, $84, $0d, $89, $4d, $86, $13, $89, $4d, $84, $0d, $89, $4d, $86, $13, $89, $4d, $84, $0f, $89, $4d, $86, $13
	.byte $89, $4d, $84, $0d, $89, $4d, $0f, $89, $4d, $0d, $89, $4d, $86, $13, $89, $4d, $84, $0f, $89, $4d, $86, $13, $89, $4d
	.byte $41, $18
	.word @song0ref288
	.byte $4d
	.byte $41, $18
	.word @song0ref288
	.byte $4d
	.byte $41, $18
	.word @song0ref288
	.byte $4d
	.byte $41, $18
	.word @song0ref288
	.byte $4d
	.byte $41, $18
	.word @song0ref288
	.byte $4d
	.byte $41, $18
	.word @song0ref288
	.byte $4d
	.byte $41, $18
	.word @song0ref288
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $10
	.word @song0ref267
@song0ch4loop:
@song0ref370:
	.byte $04, $c5, $02, $ad, $09, $95, $07, $ad, $06, $95, $09, $95, $02, $ad, $08, $89, $01, $89, $0a, $89, $03, $89, $07, $89
	.byte $06, $89, $09, $89, $02, $95, $09, $a1, $04, $ad, $06, $95, $09, $89, $05, $89, $02, $ad
	.byte $41, $2a
	.word @song0ref370
	.byte $42
	.word @song0ch4loop
