; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_abyssmodding_settings:=music_data_abyssmodding_settings

music_data_abyssmodding_settings:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Abyssmodding (Settings)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_abyssmodding_settings
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env19,@env12,@env8,@env0 ; 00 : Bass
	.word @env11,@env12,@env15,@env2 ; 01 : Triangle Drums
	.word @env9,@env12,@env14,@env0 ; 02 : Plain
	.word @env16,@env12,@env3,@env0 ; 03 : Lead
	.word @env16,@env18,@env3,@env0 ; 04 : Lead 2
	.word @env1,@env12,@env14,@env0 ; 05 : Noise Percussion 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $80,$ff,$00,$01
@env3:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env4:
	.byte $cc,$cc,$c0,$00,$01
@env5:
	.byte $00,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$00,$01
@env6:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$03,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$01
@env7:
	.byte $d8,$cc,$c0,$b4,$00,$03
@env8:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $bc,$b8,$b8,$c0,$00,$02
@env11:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env12:
	.byte $c0,$7f,$00,$01
@env13:
	.byte $c0,$05,$c1,$05,$c2,$05,$c3,$05,$c2,$05,$c1,$04,$c1,$00,$00
@env14:
	.byte $7f,$00,$00
@env15:
	.byte $c2,$7f,$00,$00
@env16:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env17:
	.byte $fc,$80,$c0,$00,$02
@env18:
	.byte $cc,$c0,$00,$01
@env19:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:
	.byte $14+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$0c,$40 ; 00 abyssgarding_dmc 3 - flixelNote v1 E# (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$01,$40 ; 01 flixelNote v1 D# (Pitch:1)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$05,$40 ; 02 flixelNote v1 D# (Pitch:5)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$08,$40 ; 03 flixelNote v1 D# (Pitch:8)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0b,$40 ; 04 flixelNote v1 D# (Pitch:11)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$07,$40 ; 05 flixelNote v1 E (Pitch:7)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0c,$40 ; 06 flixelNote v1 E (Pitch:12)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $86
@song0ref2:
	.byte $12, $99, $19, $99, $1d, $99, $12, $99, $19, $99, $1d, $99, $48
@song0ref15:
	.byte $12, $99, $19, $99, $1e, $99, $12, $99, $19, $99, $1e, $99, $48
	.byte $41, $18
	.word @song0ref2
	.byte $48
	.byte $41, $18
	.word @song0ref2
	.byte $48
	.byte $41, $18
	.word @song0ref2
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $4e, $00, $1e, $99, $1d, $99, $1e, $99, $23, $99, $22, $99
	.byte $20, $99, $48, $1d, $ff, $a5, $48, $20, $b5, $22, $99, $25, $99, $23, $99, $22, $99, $48, $20, $8b, $1e, $8b, $20, $8b
	.byte $22, $8b, $1e, $8b, $1d, $8b, $1e, $8b, $20, $8b, $25, $8b, $23, $8b, $22, $8b, $20, $8b, $48, $1e, $ff, $89, $2a, $99
	.byte $48, $1e, $ed, $1b, $99, $1d, $99, $48, $1e, $ff, $89, $2a, $99, $48, $1e, $b5, $1d, $99, $1e, $99, $1b, $8b, $1d, $8b
	.byte $22, $8b, $20, $8b, $42
	.word @song0ch0loop
@song0ch1:
	.byte $4e, $01
	.byte $41, $0c
	.word @song0ref1
	.byte $41, $0c
	.word @song0ref15
	.byte $4e, $01
	.byte $41, $0c
	.word @song0ref2
	.byte $41, $0c
	.word @song0ref15
	.byte $4e, $01
	.byte $41, $0c
	.word @song0ref2
	.byte $41, $0c
	.word @song0ref15
	.byte $4e, $01
	.byte $41, $0c
	.word @song0ref2
	.byte $41, $0c
	.word @song0ref15
@song0ch1loop:
	.byte $80, $06, $ff, $89, $12, $99, $06, $ed, $03, $99, $05, $99, $06, $ff, $89, $12, $99, $06, $b5, $05, $99, $06, $99, $03
	.byte $99, $05, $99, $03, $ff, $89, $0f, $99, $03, $ed, $40, $0b, $99, $01, $99, $03, $ff, $89, $0f, $99, $03, $b5, $01, $99
	.byte $03, $99, $0a, $99, $08, $99, $42
	.word @song0ch1loop
@song0ch2:
	.byte $4e, $01, $88
@song0ref227:
	.byte $1e, $99, $25, $99, $29, $99, $1e, $99, $25, $99, $29, $99, $1e, $99, $25, $99, $2a, $99, $1e, $99, $25, $99, $2a, $99
	.byte $4e, $01
	.byte $41, $18
	.word @song0ref227
	.byte $4e, $01
	.byte $41, $18
	.word @song0ref227
	.byte $4e, $01
	.byte $41, $18
	.word @song0ref227
@song0ch2loop:
@song0ref267:
	.byte $82, $25, $8b, $80, $12, $c3, $82, $31, $8b, $84, $12, $a7, $80, $1e, $99, $82, $25, $8b, $80, $12, $c3, $82, $31, $8b
	.byte $84, $12, $8b, $80, $0f, $99, $11, $99
	.byte $41, $0d
	.word @song0ref267
	.byte $a7, $11, $99, $82, $31, $8b, $80, $12, $8b, $0f, $99, $11
@song0ref314:
	.byte $99, $82, $25, $8b, $80, $0f, $c3, $82, $31, $8b, $84, $0f, $a7, $80, $1b, $99, $82, $25, $8b, $80, $0f, $c3, $82, $31
	.byte $8b, $84, $0f, $8b, $80, $0b, $99, $0d
	.byte $41, $0e
	.word @song0ref314
	.byte $a7, $0d, $99, $82, $31, $8b, $80, $0f, $8b, $16, $99, $14, $99, $42
	.word @song0ch2loop
@song0ch3:
	.byte $4b, .lobyte(@env4), .hibyte(@env4), $8a
@song0ref369:
	.byte $23, $b5, $4b, .lobyte(@env18), .hibyte(@env18), $23, $99, $4d, $2f, $99, $4d, $23, $b5, $4b, .lobyte(@env4), .hibyte(@env4)
	.byte $23, $b5, $4b, .lobyte(@env18), .hibyte(@env18), $23, $99, $4d, $2f, $99, $4d, $23, $b5, $4b, .lobyte(@env4), .hibyte(@env4)
	.byte $41, $10
	.word @song0ref369
	.byte $4b, .lobyte(@env4), .hibyte(@env4)
	.byte $41, $10
	.word @song0ref369
	.byte $4b, .lobyte(@env4), .hibyte(@env4)
	.byte $41, $10
	.word @song0ref369
@song0ch3loop:
	.byte $4c
@song0ref418:
	.byte $4b, .lobyte(@env10), .hibyte(@env10), $0d, $99, $4b, .lobyte(@env18), .hibyte(@env18), $13, $99, $4d, $13, $99, $4b
	.byte .lobyte(@env7), .hibyte(@env7), $0f, $99, $4b, .lobyte(@env18), .hibyte(@env18), $13, $99, $4d, $13, $99, $4b, .lobyte(@env10)
	.byte .hibyte(@env10), $0d, $8b, $4b, .lobyte(@env18), .hibyte(@env18), $13, $8b, $4d, $13, $8b, $4d, $13, $8b, $4d, $13
	.byte $8b, $4d, $13, $8b, $4b, .lobyte(@env7), .hibyte(@env7), $0f, $8b, $4b, .lobyte(@env18), .hibyte(@env18), $13, $8b
	.byte $4d, $13, $8b, $4d, $13, $8b, $4d, $13, $8b, $4d, $13, $8b, $4b, .lobyte(@env10), .hibyte(@env10), $0d, $b5, $4b, .lobyte(@env18)
	.byte .hibyte(@env18), $13, $99, $4b, .lobyte(@env7), .hibyte(@env7), $0f, $b5, $4b, .lobyte(@env18), .hibyte(@env18), $13
	.byte $99, $4b, .lobyte(@env10), .hibyte(@env10), $0d, $99, $4b, .lobyte(@env18), .hibyte(@env18), $13, $8b, $4d, $13, $99
	.byte $4d, $13, $8b, $4b, .lobyte(@env7), .hibyte(@env7), $0f, $99, $4b, .lobyte(@env18), .hibyte(@env18), $13, $8b, $4d
	.byte $13, $99, $4d, $13, $8b
	.byte $41, $3c
	.word @song0ref418
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ref546:
	.byte $04, $99, $05, $99, $07, $99, $04, $99, $05, $99, $07, $99, $04, $99, $05, $99, $01, $99, $04, $99, $05, $99, $01, $99
	.byte $41, $18
	.word @song0ref546
	.byte $41, $18
	.word @song0ref546
	.byte $41, $18
	.word @song0ref546
@song0ch4loop:
@song0ref580:
	.byte $02, $99, $03, $99, $06, $99, $02, $99, $03, $99, $06, $99, $02, $99, $03, $99, $04, $99, $02, $99, $03, $99, $04, $99
	.byte $41, $18
	.word @song0ref580
	.byte $41, $18
	.word @song0ref580
	.byte $41, $18
	.word @song0ref580
	.byte $42
	.word @song0ch4loop
