; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1

.export _music_data_super_fwmc:=music_data_super_fwmc

music_data_super_fwmc:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : SUPER FWMC
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_super_fwmc
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env16,@env18,@env0 ; 00 : Noise Percussion 1
	.word @env14,@env16,@env19,@env2 ; 01 : Triangle Drums
	.word @env12,@env15,@env18,@env21 ; 02 : Recca Tri Note OFF 1
	.word @env3,@env16,@env18,@env0 ; 03 : Noise Percussion 2
	.word @env12,@env6,@env19,@env0 ; 04 : Journey to Silius Tom
	.word @env12,@env10,@env19,@env0 ; 05 : Journey to Silius Tom (Fill)
	.word @env24,@env23,@env11,@env0 ; 06 : Slap Bass
	.word @env20,@env23,@env7,@env0 ; 07 : Lead 2
	.word @env5,@env16,@env18,@env0 ; 08 : Fade 1
	.word @env13,@env16,@env18,@env0 ; 09 : Noise Percussion 3

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $80,$ff,$00,$01
@env3:
	.byte $00,$cf,$ca,$c5,$c0,$00,$04
@env4:
	.byte $fc,$c0,$00,$01
@env5:
	.byte $04,$cf,$00,$01,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$12
@env6:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$00,$08
@env7:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env8:
	.byte $00,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$00,$01
@env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$03,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$01
@env10:
	.byte $c0,$bf,$c0,$c1,$00,$03
@env11:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env12:
	.byte $00,$cf,$7f,$00,$02
@env13:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$09
@env14:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env15:
	.byte $c0,$7f,$7f,$c1,$00,$00
@env16:
	.byte $c0,$7f,$00,$01
@env17:
	.byte $c0,$05,$c1,$05,$c2,$05,$c3,$05,$c2,$05,$c1,$04,$c1,$00,$00
@env18:
	.byte $7f,$00,$00
@env19:
	.byte $c2,$7f,$00,$00
@env20:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env21:
	.byte $00,$b2,$7f,$00,$02
@env22:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@env23:
	.byte $cc,$c0,$00,$01
@env24:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$09,$00 ; 00 flixelNote v1 D (Pitch:9)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$02,$00 ; 01 flixelNote v1 D# (Pitch:2)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$05,$00 ; 02 flixelNote v1 D# (Pitch:5)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$06,$00 ; 03 flixelNote v1 D# (Pitch:6)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0b,$00 ; 04 flixelNote v1 D# (Pitch:11)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$03,$00 ; 05 flixelNote v1 E (Pitch:3)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$07,$00 ; 06 flixelNote v1 E (Pitch:7)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$09,$00 ; 07 flixelNote v1 E (Pitch:9)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $51, $e0, $50, $8e, $14, $87, $ff, $95, $48, $14, $ff, $9d, $48, $14, $ff, $9d, $48, $88, $12, $87, $00, $87, $12, $87
	.byte $00, $87, $15, $87, $00, $87, $12, $87, $00, $87, $12, $87, $00, $87, $12, $87, $00, $87, $15, $87, $00, $87, $12, $87
	.byte $00, $87, $48, $7f
	.byte $41, $2a
	.word @song0ref1
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f
@song0ref61:
	.byte $8e
@song0ref62:
	.byte $20, $91, $45, $91, $20, $91, $45, $91, $20, $91, $20, $91, $22, $a5, $48, $24, $a5, $45, $91, $24, $9b, $45, $9b, $24
	.byte $a5, $48, $20, $91, $45, $91, $20, $91, $45, $91, $20, $91, $20, $91, $22, $a5, $48, $27, $91, $20, $91, $27, $91, $20
	.byte $91, $27, $91, $20, $91, $27, $91, $20, $91, $48
	.byte $41, $36
	.word @song0ref62
	.byte $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $00, $90, $20, $91, $45, $91, $20, $91, $45, $91, $20, $91, $1b
	.byte $91, $20, $a5, $48, $22, $a5, $49, .lobyte(@env22), .hibyte(@env22), $e3, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $90, $16, $91, $48, $24, $91, $45, $91, $24, $91, $45, $91, $24, $91, $25, $91, $24, $91, $20, $91, $48, $22, $a5, $49
	.byte .lobyte(@env22), .hibyte(@env22), $e3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $45, $91, $48, $90, $08, $a5, $22
	.byte $91, $45, $91, $22, $91, $45, $91, $20, $91, $45, $91, $48, $20, $91, $45, $87, $1d, $87, $20, $91, $45, $87, $20, $91
	.byte $45, $87, $20, $91, $14, $91, $11, $91, $48, $13, $a5, $45, $91, $11, $87, $13, $87, $14, $87, $16, $87, $18, $87, $19
	.byte $87, $16, $91, $13, $87, $92, $14, $87, $48, $90, $14, $a5, $45, $91, $14, $a5, $45, $91, $14, $91, $45, $91, $48
	.byte $41, $36
	.word @song0ref61
	.byte $48
	.byte $41, $36
	.word @song0ref62
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ref275:
	.byte $8c
@song0ref276:
	.byte $08, $91, $00, $87, $0c, $91, $00, $87, $0f, $91, $00, $91, $08, $91, $0c, $91, $0f, $91
	.byte $41, $12
	.word @song0ref276
	.byte $41, $12
	.word @song0ref276
@song0ref300:
	.byte $88, $1a, $85, $00, $1a, $85, $00, $12, $85, $00, $0e, $85, $00, $1a, $85, $00, $12, $85, $00, $12, $85, $00, $0e, $85
	.byte $00, $8a, $1a, $83, $1a, $85, $1a, $83, $88, $1a, $85, $00, $1a, $85, $00, $12, $85, $00, $12, $85, $00, $0e, $85, $00
	.byte $0e, $85, $00
	.byte $41, $12
	.word @song0ref275
	.byte $41, $12
	.word @song0ref276
	.byte $41, $12
	.word @song0ref276
	.byte $41, $30
	.word @song0ref300
@song0ch1loop:
	.byte $7f
@song0ref365:
	.byte $8c
@song0ref366:
	.byte $08, $91, $78, $08, $87, $7f, $0c, $91, $78, $0c, $87, $7f, $0f, $91, $78, $0f, $91, $7f, $08, $91, $0c, $91, $0f, $91
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $30
	.word @song0ref300
	.byte $41, $12
	.word @song0ref365
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $30
	.word @song0ref300
	.byte $41, $12
	.word @song0ref365
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $12
	.word @song0ref366
	.byte $41, $30
	.word @song0ref300
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ref462:
	.byte $82, $25, $87, $84, $40, $60, $87, $82, $25, $87, $84, $40, $60, $87, $82, $31, $87, $84, $40, $60, $87, $82, $25, $87
	.byte $31, $87, $84, $40, $60, $87, $40, $60, $87, $82, $25, $87, $84, $40, $60, $87, $82, $31, $87, $84, $40, $60, $87, $82
	.byte $25, $87, $84, $40, $60, $87
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
@song0ref522:
	.byte $88, $26, $85, $00, $26, $85, $00, $1e, $85, $00, $1a, $85, $00, $26, $85, $00, $1e, $85, $00, $1e, $85, $00, $1a, $85
	.byte $00, $8a, $26, $83, $26, $85, $26, $83, $88, $26, $85, $00, $26, $85, $00, $1e, $85, $00, $1e, $85, $00, $1a, $85, $00
	.byte $1a, $85, $00
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $30
	.word @song0ref522
@song0ch2loop:
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $30
	.word @song0ref522
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $30
	.word @song0ref522
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $20
	.word @song0ref462
	.byte $41, $30
	.word @song0ref522
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ref661:
	.byte $4f, $00, $80
@song0ref664:
	.byte $0d, $87, $86, $13, $87, $80, $0d, $87, $86, $13, $87, $80, $0f, $87, $86, $13, $87, $80, $0d, $87, $0f, $87, $86, $13
	.byte $87, $13, $87, $80, $0d, $87, $86, $13, $87, $80, $0f, $87, $86, $13, $87, $80, $0d, $87, $86, $13, $87
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
@song0ref715:
	.byte $4f, $01, $80, $2a, $87, $2a, $87, $28, $87, $27, $87, $2a, $87, $28, $87, $28, $87, $27, $87, $4f, $03, $2c, $87, $2b
	.byte $87, $2a, $87, $29, $87, $28, $87, $28, $87, $27, $87, $27, $87, $4f, $00
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref715
@song0ch3loop:
	.byte $4f, $00
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref715
	.byte $4f, $00
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref715
	.byte $4f, $00
	.byte $41, $20
	.word @song0ref664
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref661
	.byte $41, $20
	.word @song0ref715
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
@song0ch4loop:
@song0ref865:
	.byte $02, $91, $01, $91, $02, $91, $01, $91, $02, $91, $01, $91, $02, $91, $01, $91, $06, $91, $08, $91, $06, $91, $08, $91
	.byte $06, $91, $08, $91, $06, $91, $08, $91, $02, $91, $01, $91, $02, $91, $01, $91, $02, $91, $01, $91, $02, $91, $01, $91
	.byte $03, $91, $05, $91, $03, $91, $05, $91, $03, $91, $05, $91, $03, $91, $05, $91
	.byte $41, $40
	.word @song0ref865
	.byte $41, $40
	.word @song0ref865
	.byte $41, $40
	.word @song0ref865
@song0ref938:
	.byte $02, $91, $04, $91, $02, $91, $04, $91, $02, $91, $04, $91, $02, $91, $04, $91, $06, $91, $07, $91, $06, $91, $07, $91
	.byte $06, $91, $07, $91, $06, $91, $07, $91, $02, $91, $04, $91, $02, $91, $04, $91, $02, $91, $04, $91, $02, $91, $04, $91
	.byte $03, $91, $01, $91, $03, $91, $01, $91, $03, $91, $01, $91, $03, $91, $01, $91
	.byte $41, $40
	.word @song0ref938
	.byte $42
	.word @song0ch4loop
