; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_world_1_levels_enter:=music_data_world_1_levels_enter

music_data_world_1_levels_enter:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : World 1 Levels Enter
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_world_1_levels_enter
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env5,@env1,@env0 ; 00 : Lead
	.word @env8,@env5,@env3,@env0 ; 01 : Bass
	.word @env4,@env5,@env6,@env0 ; 02 : Plain

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env2:
	.byte $00,$c0,$b9,$b5,$b6,$bc,$c4,$ca,$cb,$c7,$00,$01
@env3:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env8:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $79, $80, $17, $9b, $74, $9d, $79, $19, $9b, $1a, $9b, $1c, $b9, $48, $17, $b9, $51, $04, $f0, $bb, $51, $f8, $00, $bb
	.byte $44, $00
@song0ch1:
	.byte $79, $82, $0b, $9b, $74, $9d, $79, $0b, $9b, $0d, $9b, $0e, $b9, $0b, $b9, $51, $04, $f0, $bb, $51, $f8, $00, $bb, $44
	.byte $00
@song0ch2:
	.byte $84, $0b, $9b, $40, $0b, $9b, $17, $9b, $15, $9b, $13, $ab, $50, $80, $17, $23, $8b, $49, .lobyte(@env2), .hibyte(@env2)
	.byte $17, $ff, $b1, $44, $00
@song0ch4:
@song0ch3:
	.byte $ff, $b3, $ff, $b3, $44, $00
