; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1

.export _music_data_death:=music_data_death

music_data_death:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Death
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_death
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env5,@env6,@env0 ; 00 : Fade
	.word @env4,@env5,@env6,@env0 ; 01 : Fade 2
	.word @env3,@env5,@env6,@env0 ; 02 : Plain

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$10
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $c0,$cc,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0f,$0f,$00 ; 00 FamiStudio Metro (Pitch:15)
	.byte $04+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$00 ; 01 FamiStudio Metro 1 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $80, $2e, $95, $2a, $95, $27, $95, $22, $95, $1e, $95, $1b, $95, $16, $95, $12, $95, $48, $82, $0f, $ff, $bd, $44, $00
@song0ch1:
	.byte $78, $4e, $01, $8b
	.byte $41, $0f
	.word @song0ref1
	.byte $89, $8b, $82, $0f, $ff, $b1, $44, $00
@song0ch2:
	.byte $41, $10
	.word @song0ref1
	.byte $82, $0f, $ff, $bd, $44, $00
@song0ch3:
	.byte $4b, .lobyte(@env7), .hibyte(@env7), $84, $23, $89, $4b, .lobyte(@env5), .hibyte(@env5), $4c, $22, $89, $21, $89, $20
	.byte $89, $1f, $89, $1e, $89, $1d, $89, $1c, $89, $1b, $89, $1a, $89, $19, $89, $28, $89, $27, $89, $26, $89, $25, $89, $24
	.byte $89, $51, $fd, $00, $ff, $bf, $44, $00
@song0ch4:
	.byte $02, $89, $52, $80, $97, $01, $89, $52, $80, $97, $01, $89, $52, $80, $97, $01, $89, $52, $80, $97, $01, $89, $52, $80
	.byte $8b, $01, $89, $52, $80, $8b, $02, $89, $52, $80, $a3, $01, $89, $52, $80, $a3, $01, $89, $52, $80, $a3, $01, $89, $52
	.byte $80, $a3, $44, $00
