; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_NOISE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1

.export _music_data_underworldreal_abyss_world_1_levels:=music_data_underworldreal_abyss_world_1_levels

music_data_underworldreal_abyss_world_1_levels:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Underworld/REAL Abyss (World 1 Levels)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_underworldreal_abyss_world_1_levels
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env17,@env10,@env6,@env0 ; 00 : Bass
	.word @env9,@env10,@env13,@env2 ; 01 : Triangle Drums
	.word @env8,@env10,@env12,@env0 ; 02 : Noise Percussion 3
	.word @env1,@env10,@env12,@env0 ; 03 : Noise Percussion 1
	.word @env7,@env10,@env12,@env0 ; 04 : Plain
	.word @env14,@env10,@env3,@env0 ; 05 : Lead

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $80,$ff,$00,$01
@env3:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env4:
	.byte $00,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$00,$01
@env5:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$03,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$01
@env6:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$09
@env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $c0,$05,$c1,$05,$c2,$05,$c3,$05,$c2,$05,$c1,$04,$c1,$00,$00
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $c2,$7f,$00,$00
@env14:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env15:
	.byte $fc,$80,$c0,$00,$02
@env16:
	.byte $cc,$c0,$00,$01
@env17:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$09,$40 ; 00 flixelNote v1 D (Pitch:9)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$06,$40 ; 01 flixelNote v1 D# (Pitch:6)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$08,$40 ; 02 flixelNote v1 D# (Pitch:8)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0b,$40 ; 03 flixelNote v1 D# (Pitch:11)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$09,$40 ; 04 flixelNote v1 E (Pitch:9)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $8a
@song0ref2:
	.byte $1b, $db, $22, $9b, $25, $9d, $22, $9b, $48, $1b, $bb, $1e, $bb, $22, $bb, $48, $27, $9d, $25, $9b, $23, $9d, $1b, $9b
	.byte $1e, $9d, $20, $9b, $48, $1b, $bb, $1e, $bb, $22, $bb, $48, $1e, $f9, $20, $bb, $48, $1d, $bb, $1e, $9d, $20, $8d, $1e
	.byte $8b, $1d, $bb, $48, $1b, $f9, $19, $9d, $1d, $9b, $48, $1b, $bb, $19, $9d, $1d, $9b, $1b, $9d, $43, $50, $cb, $27, $60
	.byte $9b
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $3b
	.word @song0ref2
	.byte $bb, $42
	.word @song0ch0loop
@song0ch1:
	.byte $7a, $4e, $00
@song0ref89:
	.byte $80
@song0ref90:
	.byte $0f, $db, $19, $bb, $05, $9b, $0f, $8d, $03, $8d, $0f, $8d, $03, $8b, $12, $8d, $03, $8d, $12, $8d, $03, $8b, $14, $8d
	.byte $03, $8d, $14, $8d, $03, $8b, $4e, $00
	.byte $41, $1e
	.word @song0ref90
@song0ref125:
	.byte $12, $9d, $43, $50, $5c, $1e, $12, $9b, $50, $a4, $12, $1e, $9d, $12, $9b, $43, $50, $5c, $1e, $12, $9d, $50, $a4, $12
	.byte $1e, $9b, $16, $bb, $17, $9d, $16, $9b, $14, $bb, $17, $9d, $19, $9b, $16, $9d, $14, $9b, $11, $bb, $51, $fc, $40
@song0ref172:
	.byte $4e, $02
@song0ref174:
	.byte $0f, $8d, $1b, $8d, $03, $8d, $1b, $8b, $0f, $8d, $1b, $8d, $03, $8d, $1b, $8b, $51, $04, $a0, $0f, $8d, $1b, $8d, $03
	.byte $8d, $1b, $8b
@song0ch1loop:
	.byte $7a, $4e, $00
	.byte $41, $1e
	.word @song0ref90
	.byte $4e, $00
	.byte $41, $1e
	.word @song0ref90
	.byte $41, $1e
	.word @song0ref125
	.byte $41, $10
	.word @song0ref172
	.byte $0f, $8d, $1b, $8d, $03, $8d, $1b, $8b, $42
	.word @song0ch1loop
@song0ch2:
	.byte $41, $1e
	.word @song0ref89
	.byte $41, $1e
	.word @song0ref90
	.byte $41, $1e
	.word @song0ref125
	.byte $41, $10
	.word @song0ref174
	.byte $0f, $8d, $1b, $8d, $03, $8d, $1b, $8b
@song0ch2loop:
@song0ref251:
	.byte $82, $25, $8d, $80, $0f, $ab, $82, $31, $8d, $88, $0f, $8d, $80, $19, $9b, $82, $31, $8d, $88, $19, $8d, $80, $05, $9b
	.byte $82, $25, $81, $80, $0f, $89, $03, $8d, $0f, $8d, $03, $8b, $82, $31, $89, $80, $12, $81, $03, $8d, $12, $8d, $03, $8b
	.byte $82, $31, $89, $80, $14, $81, $03, $8d, $14, $8d, $03, $8b
	.byte $41, $2e
	.word @song0ref251
	.byte $82, $25, $8d, $80, $12, $8d, $43, $50, $5c, $1e, $12, $9b, $82, $31, $8d, $88, $50, $b4, $18, $1e, $8d, $80, $12, $9b
	.byte $82, $31, $8d, $88, $50, $6c, $18, $12, $8d, $80, $50, $a4, $12, $1e, $9b, $82, $25, $8d, $80, $16, $ab, $82, $31, $8d
	.byte $80, $17, $8d, $16, $9b, $82, $31, $8d, $80, $14, $ab, $82, $25, $8d, $80, $17, $8d, $19, $9b, $82, $31, $8d, $80, $16
	.byte $8d, $14, $9b, $82, $31, $8d, $80, $11, $ab, $82, $25, $81, $80, $0f, $89
@song0ref401:
	.byte $1b, $8d, $03, $8d, $1b, $8b, $82, $31, $89, $80, $0f, $81
	.byte $41, $0a
	.word @song0ref401
	.byte $1b, $8d, $03, $8d, $1b, $8b, $42
	.word @song0ch2loop
@song0ch3:
	.byte $71, $88, $23, $ff, $b7
@song0ref430:
	.byte $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $4f, $01, $fb, $51, $08, $f0, $50, $fa, $2f, $25, $bb
@song0ch3loop:
	.byte $4c, $7f, $4b, .lobyte(@env16), .hibyte(@env16), $4f, $00, $84
@song0ref462:
	.byte $0d, $8d, $4d, $86, $13, $8d, $4d, $13, $8d, $4d, $13, $8b, $4d, $84, $0f, $8d, $4d, $86, $13, $8d, $4d, $13, $8d, $4d
	.byte $13, $8b, $4d, $84, $0f, $8d, $4d, $86, $13, $8d, $4d, $13, $8d, $4d, $13, $8b, $4d, $4f, $00, $84, $0d, $91, $4d, $13
	.byte $95, $4d, $13, $8f, $4d, $0f, $91, $4d, $13, $95, $4d, $13, $8f, $4d, $0f, $91, $4d, $13, $95, $4d, $13, $8f, $4d, $4f
	.byte $00
	.byte $41, $2a
	.word @song0ref462
	.byte $4d, $4f, $00
	.byte $41, $2a
	.word @song0ref462
	.byte $4d, $4f, $00
	.byte $41, $2a
	.word @song0ref462
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $0c
	.word @song0ref430
	.byte $ff, $b9, $ff, $b9
@song0ch4loop:
@song0ref561:
	.byte $02, $9d, $03, $9b, $02, $9d, $05, $9b, $03, $9d, $05, $9b
	.byte $41, $0c
	.word @song0ref561
	.byte $41, $0c
	.word @song0ref561
	.byte $41, $0c
	.word @song0ref561
	.byte $03, $9d, $05, $9b, $03, $9d, $04, $9b, $05, $9d, $04, $9b, $03, $9d, $01, $9b, $03, $9d, $04, $9b, $01, $9d, $04, $9b
	.byte $41, $0c
	.word @song0ref561
	.byte $41, $0c
	.word @song0ref561
	.byte $42
	.word @song0ch4loop
