; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_no_more_bau_bau_c_game_over:=music_data_no_more_bau_bau_c_game_over

music_data_no_more_bau_bau_c_game_over:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : No More BAU BAU :C (Game Over)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_no_more_bau_bau_c_game_over
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env7,@env9,@env0 ; 00 : Noise Percussion 3
	.word @env10,@env7,@env2,@env0 ; 01 : Lead
	.word @env14,@env7,@env3,@env0 ; 02 : Bass
	.word @env11,@env7,@env8,@env0 ; 03 : Noise Cymbal
	.word @env6,@env7,@env5,@env0 ; 04 : Noise Cymbal 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $cc,$c0,$c4,$c4,$c8,$02,$c9,$c8,$00,$06
@env2:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env3:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env4:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$09
@env5:
	.byte $c1,$03,$c0,$02,$c0,$c0,$00,$04
@env6:
	.byte $00,$cf,$03,$ce,$03,$cd,$03,$cc,$03,$cb,$03,$ca,$03,$c9,$03,$c8,$03,$c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$03,$c0,$00,$1f
@env7:
	.byte $c0,$7f,$00,$01
@env8:
	.byte $c1,$02,$c1,$c0,$00,$02
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env11:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1f
@env12:
	.byte $c0,$cc,$00,$00
@env13:
	.byte $cc,$c0,$00,$01
@env14:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $82, $1e, $ff, $8d, $20, $c5, $48, $19, $ff, $8d, $1c, $c5, $48, $20, $a1
@song0ref16:
	.byte $1e, $a1, $20, $a1, $1e, $a1, $20, $a1, $1b, $a1, $48, $19, $ff, $8d, $1c, $c5, $48
	.byte $41, $08
	.word @song0ref16
	.byte $1e, $a1, $1c, $a1, $48, $23, $a1, $1c, $a1, $23, $a1, $1c, $a1, $23, $a1, $25, $a1, $48, $23, $c5, $1e, $a1, $1c, $a1
	.byte $1b, $c5, $48, $19, $ff, $d5, $48, $51, $fd, $00, $19, $ff, $d5, $44, $00
@song0ch1:
	.byte $7a, $84
@song0ref78:
	.byte $14, $ff, $8d, $12, $c5, $0d, $ff, $d5
	.byte $41, $08
	.word @song0ref78
	.byte $15, $ff, $8d, $12, $c5, $10, $ff, $8d, $19, $c5, $17, $ff, $8d, $12, $c5, $14, $c5, $15, $c5, $17, $c5, $51, $03, $f0
	.byte $4b, .lobyte(@env12), .hibyte(@env12), $0d, $c5, $51, $fc, $00, $ff, $8f, $44, $00
@song0ch2:
	.byte $4b, .lobyte(@env13), .hibyte(@env13), $80
@song0ref130:
	.byte $19, $c5, $4d, $0d, $c5, $4d, $0d, $c5, $4d, $19, $c5, $4d, $0d, $c5, $4d, $0d, $c5, $4d
	.byte $41, $0c
	.word @song0ref130
	.byte $4d
	.byte $41, $0c
	.word @song0ref130
	.byte $4d
	.byte $41, $0c
	.word @song0ref130
	.byte $4d, $86, $0d, $ff, $d5, $44, $00
@song0ch3:
	.byte $4b, .lobyte(@env13), .hibyte(@env13), $80
@song0ref171:
	.byte $13, $c5, $4d, $13, $c5, $4d, $13, $c5, $4d, $13, $c5, $4d
	.byte $41, $08
	.word @song0ref171
	.byte $4d
	.byte $41, $08
	.word @song0ref171
	.byte $4d
	.byte $41, $08
	.word @song0ref171
	.byte $4d
	.byte $41, $08
	.word @song0ref171
	.byte $4d
	.byte $41, $08
	.word @song0ref171
	.byte $4b, .lobyte(@env1), .hibyte(@env1), $88, $1a, $ff, $d5, $44, $00
@song0ch4:
@song0ref212:
	.byte $ff, $d7, $ff, $d7, $ff, $d7, $ff, $d7
	.byte $41, $08
	.word @song0ref212
	.byte $ff, $d7, $44, $00
