; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_NOISE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1

.export _music_data_preabyss_title_:=music_data_preabyss_title_

music_data_preabyss_title_:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Preabyss (Title) ()
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_end), .hibyte(@tempo_env_1_end), 0, 0

.export music_data_preabyss_title_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env11,@env13,@env0 ; 00 : Noise Percussion 1
	.word @env3,@env11,@env13,@env0 ; 01 : Noise Percussion 2
	.word @env18,@env11,@env8,@env0 ; 02 : Bass
	.word @env10,@env11,@env14,@env2 ; 03 : Triangle Drums
	.word @env9,@env11,@env13,@env0 ; 04 : Plain
	.word @env15,@env11,@env5,@env0 ; 05 : Lead

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $80,$ff,$00,$01
@env3:
	.byte $00,$cf,$ca,$c5,$c0,$00,$04
@env4:
	.byte $00,$c0,$bd,$ba,$b8,$b7,$b8,$ba,$bd,$c0,$c3,$c6,$c8,$c9,$c8,$c6,$c3,$00,$01
@env5:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env6:
	.byte $00,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$00,$01
@env7:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$03,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$01
@env8:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $c0,$05,$c1,$05,$c2,$05,$c3,$05,$c2,$05,$c1,$04,$c1,$00,$00
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env16:
	.byte $c0,$cc,$00,$00
@env17:
	.byte $fc,$80,$c0,$00,$02
@env18:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$09,$40 ; 00 flixelNote v1 D (Pitch:9)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$07,$40 ; 01 flixelNote v1 D# (Pitch:7)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$08,$40 ; 02 flixelNote v1 D# (Pitch:8)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$09,$40 ; 03 flixelNote v1 D# (Pitch:9)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0a,$40 ; 04 flixelNote v1 D# (Pitch:10)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0b,$40 ; 05 flixelNote v1 D# (Pitch:11)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0c,$40 ; 06 flixelNote v1 D# (Pitch:12)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$05,$40 ; 07 flixelNote v1 E (Pitch:5)

@tempo_env_1_end:
	.byte $03,$05,$80

@song0ch0:
	.byte $4e, $fb, $84, $03, $ff, $b1, $0f, $a1, $48, $03, $ff, $8d, $40, $0b, $a1, $01, $a1, $48, $4e, $fb, $03, $ff, $b1, $0f
	.byte $a1, $48
@song0ref27:
	.byte $03, $c5, $01, $a1, $03, $a1, $40, $0b, $a1, $01, $a1, $48, $40, $0b, $ff, $b1, $0b, $a1, $48, $40, $0b, $ff, $8d, $40
	.byte $0a, $a1, $01, $a1, $48, $40, $0b, $ff, $b1, $0b, $a1, $48
@song0ref63:
	.byte $40, $0b, $c5, $40, $0a, $a1, $40, $0b, $a1, $01, $a1, $03, $a1
@song0ch0loop:
	.byte $4c, $47, .lobyte(@tempo_env_1_end), .hibyte(@tempo_env_1_end), $4e, $00, $8a
@song0ref84:
	.byte $1e, $d1, $1c, $99, $1e, $99, $20, $99, $48, $21, $b5, $20, $99, $1e, $b5, $1c, $99, $48, $1a, $b5, $45, $99, $1c, $b5
	.byte $45, $99, $48, $1e, $99, $20, $99, $21, $99, $23, $99, $20, $99, $1c, $99, $48, $4e, $00, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $1e, $d1, $4d, $1c, $99, $4d, $1e, $99, $4d, $20, $99, $48, $4d, $21, $b5, $4d, $20, $99, $4d, $1e, $b5, $4d, $1c, $99
	.byte $48, $4d, $1a, $b5, $45, $99, $4d, $1c, $b5, $45, $99, $48, $4d, $1e, $99, $4d, $20, $99, $4d, $21, $99, $4d, $23, $99
	.byte $4d, $20, $99, $4d, $1c, $99, $48, $4e, $00, $4b, .lobyte(@env11), .hibyte(@env11), $4c
	.byte $41, $48
	.word @song0ref84
	.byte $48, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $1e
@song0ref199:
	.byte $b5, $21, $b5, $23, $b5, $48, $25, $b5, $23, $b5, $21, $b5, $48, $20, $b5, $23, $b5, $25, $b5, $48, $26, $b5, $25, $b5
	.byte $23, $8b, $21, $8b, $20, $8b, $1e, $8b, $48, $1c
	.byte $41, $0b
	.word @song0ref199
	.byte $48
@song0ref237:
	.byte $10, $8b, $1c, $8b, $12, $8b, $1e, $8b, $0e, $8b, $1a, $8b
	.byte $41, $0c
	.word @song0ref237
	.byte $48, $1e, $b5, $20, $b5, $1a, $b5, $42
	.word @song0ch0loop
@song0ch1:
	.byte $84, $03, $ff, $b1, $0f, $a1, $03, $ff, $8d, $40, $0b, $a1, $01, $a1, $03, $ff, $b1, $0f, $a1
	.byte $41, $0a
	.word @song0ref27
	.byte $40, $0b, $ff, $b1, $0b, $a1, $40, $0b, $ff, $8d, $40, $0a, $a1, $01, $a1, $40, $0b, $ff, $b1, $0b, $a1
	.byte $41, $0a
	.word @song0ref63
@song0ch1loop:
@song0ref309:
	.byte $06, $b5, $04, $99, $06, $b5, $08, $99, $09, $b5, $08, $b5, $06, $b5, $06, $b5, $04, $99, $06, $b5, $08, $99, $06, $99
	.byte $0b, $b5, $0a, $8b, $09, $8b, $08, $b5
	.byte $41, $20
	.word @song0ref309
	.byte $41, $20
	.word @song0ref309
	.byte $41, $20
	.word @song0ref309
	.byte $06, $ff, $a5, $00, $ff, $a5, $08, $ff, $a5, $00, $ff, $a5, $04, $ff, $a5, $00, $ff, $a5, $04, $b5, $43, $50, $33, $10
	.byte $0e, $8b, $43, $02, $8b, $06, $b5, $43, $50, $60, $12, $0e, $8b, $43, $02, $8b, $00, $ff, $a5, $42
	.word @song0ch1loop
@song0ch2:
	.byte $49, .lobyte(@env4), .hibyte(@env4), $84, $0f, $ff, $b1, $84, $1b, $a1, $0f, $ff, $8d, $0b, $a1, $0d, $a1, $49, .lobyte(@env4)
	.byte .hibyte(@env4), $0f, $ff, $b1, $84, $1b, $a1, $0f, $c5, $0d, $a1, $0f, $a1, $0b, $a1, $0d, $a1, $0b, $ff, $b1, $17
	.byte $a1, $0b, $ff, $8d, $0a, $a1, $0d, $a1, $0b, $ff, $b1, $17, $a1, $0b, $c5, $0a, $a1, $0b, $a1, $0d, $a1, $0f, $a1
@song0ch2loop:
	.byte $4c
@song0ref461:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $25, $8b, $84, $12, $a7, $86, $31, $8b, $84, $10, $8b, $12, $99, $86
	.byte $31, $8b, $84, $12, $8b, $14, $99, $86, $25, $8b, $84, $15, $a7, $86, $31, $8b, $84, $14, $a7, $86, $31, $8b, $84, $12
	.byte $a7
	.byte $41, $12
	.word @song0ref461
@song0ref508:
	.byte $84, $12, $8b, $17, $99, $86, $31, $8b, $84, $17, $8b, $16, $8b, $15, $8b, $86, $31, $8b, $84, $14, $a7
	.byte $41, $1c
	.word @song0ref461
	.byte $41, $12
	.word @song0ref461
	.byte $41, $10
	.word @song0ref508
	.byte $41, $1c
	.word @song0ref461
	.byte $41, $12
	.word @song0ref461
	.byte $41, $10
	.word @song0ref508
	.byte $41, $1c
	.word @song0ref461
	.byte $41, $12
	.word @song0ref461
	.byte $41, $10
	.word @song0ref508
	.byte $86, $25, $b5, $31, $b5, $31, $b5, $4b, .lobyte(@env16), .hibyte(@env16), $84, $06, $b5, $4d, $09, $b5, $4d, $0d, $b5
	.byte $4b, .lobyte(@env11), .hibyte(@env11), $4c, $86, $25, $b5, $31, $b5, $31, $b5, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $84, $08, $b5, $4d, $0b, $b5, $4d, $10, $99, $4d, $0b, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $86, $25, $b5
	.byte $31, $b5, $31, $b5, $4b, .lobyte(@env16), .hibyte(@env16), $84, $04, $b5, $4d, $09, $b5, $4d, $0b, $b5, $4b, .lobyte(@env11)
	.byte .hibyte(@env11), $4c, $86, $25, $b5, $31, $b5, $31, $b5, $4b, .lobyte(@env16), .hibyte(@env16), $84, $06, $b5, $4d
	.byte $08, $b5, $4d, $02, $b5, $42
	.word @song0ch2loop
@song0ch3:
@song0ref650:
	.byte $ff, $d7, $ff, $d7, $ff, $d7, $ff, $d7, $ff, $d7, $ff, $d7, $ff, $d7, $71, $4f, $01, $88, $22, $ff, $8d, $51, $07, $f0
	.byte $50, $fb, $2e, $24, $c5
@song0ch3loop:
@song0ref680:
	.byte $7f
@song0ref681:
	.byte $4f, $00, $80, $19, $8b, $82, $21, $8b, $21, $8b, $21, $8b, $80, $1d, $8b, $82, $21, $8b, $21, $8b, $21, $8b, $80, $1d
	.byte $8b, $82, $21, $8b, $21, $8b, $21, $8b
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref681
	.byte $51, $fd, $00
	.byte $41, $18
	.word @song0ref681
	.byte $41, $18
	.word @song0ref680
	.byte $51, $fa, $00, $88, $21, $d1, $51, $06, $f0, $4f, $01, $50, $fc, $2f, $25, $d1
	.byte $41, $18
	.word @song0ref681
	.byte $51, $fa, $00, $88, $21, $d1, $51, $06, $f0, $4f, $01, $50, $fc, $2f, $25, $d1
	.byte $41, $18
	.word @song0ref681
	.byte $51, $fa, $00, $88, $21, $d1, $51, $06, $f0, $4f, $01, $50, $fc, $2f, $25, $d1
	.byte $41, $18
	.word @song0ref681
	.byte $51, $fa, $00, $88, $21, $d1, $51, $06, $f0, $4f, $01, $50, $fc, $2f, $25, $d1, $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $0e
	.word @song0ref650
	.byte $ff, $d7
@song0ch4loop:
@song0ref846:
	.byte $03, $99, $04, $99, $06, $99, $03, $99, $04, $99, $06, $99, $03, $b5, $04, $b5, $06, $b5
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $41, $12
	.word @song0ref846
	.byte $01, $99, $05, $99, $07, $99, $01, $99, $05, $99, $07, $99, $01, $b5, $05, $b5, $07, $99, $05, $99, $02, $99, $04, $99
	.byte $05, $99, $02, $99, $04, $99, $05, $99, $02, $b5, $04, $b5, $05, $b5, $02, $99, $03, $99, $08, $99, $02, $99, $03, $99
	.byte $08, $99, $03, $b5, $01, $b5, $08, $b5, $42
	.word @song0ch4loop
