; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Abyssgarding:
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_miniabyss_tutorial:=music_data_miniabyss_tutorial

music_data_miniabyss_tutorial:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Miniabyss (Tutorial)
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_miniabyss_tutorial
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env17,@env11,@env8,@env0 ; 00 : Bass
	.word @env1,@env11,@env13,@env0 ; 01 : Noise Percussion 1
	.word @env10,@env11,@env14,@env2 ; 02 : Triangle Drums
	.word @env3,@env11,@env13,@env0 ; 03 : Noise Percussion 2
	.word @env9,@env11,@env13,@env0 ; 04 : Plain
	.word @env15,@env11,@env5,@env0 ; 05 : Lead

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $80,$ff,$00,$01
@env3:
	.byte $00,$cf,$ca,$c5,$c0,$00,$04
@env4:
	.byte $fc,$c0,$00,$01
@env5:
	.byte $c0,$03,$c1,$c2,$c3,$c3,$06,$c2,$06,$c1,$06,$c2,$05,$c2,$00,$05
@env6:
	.byte $00,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$00,$01
@env7:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$03,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$01
@env8:
	.byte $c0,$02,$c1,$03,$c2,$03,$c3,$03,$c2,$02,$c2,$00,$02
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $c0,$05,$c1,$05,$c2,$05,$c3,$05,$c2,$05,$c1,$04,$c1,$00,$00
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $0d,$cf,$ce,$cd,$cc,$ca,$c9,$c8,$06,$c7,$06,$00,$07,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1b
@env16:
	.byte $c0,$cc,$00,$00
@env17:
	.byte $00,$cf,$ca,$c8,$c7,$00,$04

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$09,$00 ; 00 flixelNote v1 D (Pitch:9)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$05,$00 ; 01 flixelNote v1 D# (Pitch:5)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$28,$0b,$00 ; 02 flixelNote v1 D# (Pitch:11)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0a,$00 ; 03 flixelNote v1 E (Pitch:10)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $0d, $99, $14, $99, $18, $99, $0d, $99, $14, $99, $18, $99, $48, $0d, $99, $14, $99, $19, $99, $0d, $99, $14, $99, $19
	.byte $99, $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48, $8a
@song0ref45:
	.byte $24, $b5, $22, $99, $24, $b5, $27, $99, $48, $25, $b5, $27, $99, $29, $b5, $22, $99, $48
	.byte $41, $10
	.word @song0ref45
	.byte $48, $18, $99, $45, $99, $18, $99, $45, $99, $18, $99, $45, $99, $48, $19, $99, $45, $99, $19, $99, $45, $99, $19, $99
	.byte $45, $99, $48, $18, $b5, $45, $99, $18, $b5, $45, $99, $48, $19, $b5, $45, $99, $19, $b5, $45, $99, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $75, $a9, $80
@song0ref117:
	.byte $0d, $99, $14, $99, $18, $99, $0d, $99, $14, $8b, $8d, $18, $99, $0d, $99, $14, $99, $19, $99, $0d, $99, $14, $8b, $8d
	.byte $19, $99
	.byte $41, $1a
	.word @song0ref117
	.byte $41, $1a
	.word @song0ref117
	.byte $41, $17
	.word @song0ref117
	.byte $7f
@song0ref153:
	.byte $0d, $99, $14, $99, $18, $99, $0d, $99, $14, $99, $18, $99, $0d, $99, $14, $99, $19, $99, $0d, $99, $14, $99, $19, $99
	.byte $41, $18
	.word @song0ref153
	.byte $41, $18
	.word @song0ref153
	.byte $41, $18
	.word @song0ref153
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $4c, $4b, .lobyte(@env16), .hibyte(@env16), $82
@song0ref195:
	.byte $0d, $b5, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $0d, $99, $19, $99, $0d, $b5, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $0d, $b5, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $0d, $99, $19, $99, $0d, $b5, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $41, $10
	.word @song0ref195
	.byte $80
	.byte $41, $18
	.word @song0ref153
	.byte $41, $18
	.word @song0ref153
	.byte $7f
@song0ref236:
	.byte $84, $25, $8b, $80, $19, $8b, $20, $99, $24, $99, $84, $2e, $8b, $80, $19, $8b, $20, $99, $24, $99, $84, $25, $8b, $80
	.byte $19, $8b, $20, $99, $25, $99, $84, $2e, $8b, $80, $19, $8b, $20, $99, $25, $99
	.byte $41, $20
	.word @song0ref236
	.byte $82, $24, $8b, $88, $18, $a7, $82, $24, $8b, $88, $18, $a7, $82, $24, $8b, $88, $18, $a7, $82, $25, $8b, $88, $19, $a7
	.byte $82, $25, $8b, $88, $19, $a7, $82, $25, $8b, $88, $19, $a7, $84, $25, $99, $4b, .lobyte(@env16), .hibyte(@env16), $80
	.byte $18, $95, $00, $81, $4d, $18, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $84, $31, $99, $4b, .lobyte(@env16)
	.byte .hibyte(@env16), $80, $18, $95, $00, $81, $4d, $18, $99, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $84, $25, $99
	.byte $4b, .lobyte(@env16), .hibyte(@env16), $80, $19, $93, $00, $83, $4d, $19, $99, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $4c, $84, $31, $99, $4b, .lobyte(@env16), .hibyte(@env16), $80, $19, $95, $00, $81, $4d, $19, $99, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $4c, $4b, .lobyte(@env16), .hibyte(@env16), $82
@song0ref392:
	.byte $23, $b5, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $23, $99, $2f, $99, $23, $b5, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $23, $b5, $4b, .lobyte(@env11), .hibyte(@env11), $4c, $23, $99, $2f, $99, $23, $b5, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $41, $10
	.word @song0ref392
	.byte $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $41, $10
	.word @song0ref392
	.byte $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $41, $10
	.word @song0ref392
@song0ref437:
	.byte $19, $99, $21, $99, $21, $99, $1d, $99, $21, $99, $21, $99
@song0ref449:
	.byte $19, $8b, $86, $21, $8b, $21, $8b, $21, $8b, $21, $8b, $21, $8b, $82, $1d, $8b, $86, $21, $8b, $21, $8b, $21, $8b, $21
	.byte $8b, $21, $8b, $82
	.byte $41, $24
	.word @song0ref437
	.byte $82, $0f, $b5, $0f, $b5, $0f, $b5, $0f, $b5, $0f, $b5, $0f, $b5
	.byte $41, $18
	.word @song0ref449
	.byte $82
	.byte $41, $18
	.word @song0ref449
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref504:
	.byte $02, $99, $01, $99, $04, $99, $02, $99, $01, $99, $04, $99, $02, $99, $01, $99, $03, $99, $02, $99, $01, $99, $03, $99
	.byte $41, $18
	.word @song0ref504
	.byte $41, $18
	.word @song0ref504
	.byte $41, $18
	.word @song0ref504
	.byte $41, $18
	.word @song0ref504
	.byte $41, $18
	.word @song0ref504
	.byte $41, $18
	.word @song0ref504
	.byte $41, $18
	.word @song0ref504
	.byte $42
	.word @song0ch4loop
