; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds_menu

sounds_menu:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_no
	.word @sfx_ntsc_menu_cancel
	.word @sfx_ntsc_scroll_menu
	.word @sfx_ntsc_menu_confirm
	.word @sfx_ntsc_default_sound

@sfx_ntsc_no:
	.byte $84,$ab,$85,$01,$83,$3f,$89,$f0,$01,$83,$3e,$01,$83,$3d,$01,$83
	.byte $3c,$01,$83,$3b,$01,$84,$56,$85,$03,$83,$3f,$01,$83,$3e,$01,$83
	.byte $3d,$01,$83,$3c,$01,$83,$3b,$01,$83,$3a,$01,$83,$39,$01,$83,$38
	.byte $01,$83,$37,$01,$83,$36,$01,$83,$35,$01,$83,$34,$01,$83,$33,$01
	.byte $83,$32,$01,$83,$31,$00
@sfx_ntsc_menu_cancel:
	.byte $84,$37,$85,$04,$83,$bf,$89,$f0,$01,$84,$76,$83,$be,$01,$84,$b5
	.byte $83,$bd,$01,$84,$f4,$83,$bc,$01,$84,$33,$85,$05,$83,$bb,$01,$84
	.byte $72,$83,$ba,$01,$84,$b1,$83,$b9,$01,$84,$f0,$83,$b8,$01,$84,$2f
	.byte $85,$06,$83,$b7,$01,$84,$6e,$83,$b6,$01,$84,$ad,$83,$b5,$01,$84
	.byte $ec,$83,$b4,$01,$84,$2b,$85,$07,$83,$b3,$01,$84,$6a,$83,$b2,$01
	.byte $84,$a9,$83,$b1,$01,$84,$e8,$00
@sfx_ntsc_scroll_menu:
	.byte $87,$34,$88,$00,$86,$8f,$89,$f0,$01,$87,$6a,$04,$87,$ff,$88,$07
	.byte $04,$00
@sfx_ntsc_menu_confirm:
	.byte $84,$d5,$85,$00,$83,$7f,$89,$f0,$01,$83,$be,$01,$83,$7d,$01,$83
	.byte $3c,$01,$83,$7b,$01,$83,$ba,$01,$83,$f9,$01,$83,$b8,$01,$83,$f7
	.byte $01,$83,$b6,$01,$83,$75,$01,$83,$34,$01,$83,$73,$01,$83,$b2,$01
	.byte $83,$71,$01,$00
@sfx_ntsc_default_sound:
	.byte $87,$38,$88,$00,$86,$8f,$89,$f0,$0a,$87,$70,$0a,$87,$e1,$0a,$87
	.byte $c4,$88,$01,$09,$00

.export sounds_menu
